CREATE DATABASE HOTEL_BOOKING

USE HOTEL_BOOKING

DROP TABLE IF EXISTS BOOKINGS;
DROP TABLE IF EXISTS ROOM;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS DATES;
DROP TABLE IF EXISTS HOTEL;
DROP TABLE IF EXISTS MARKET_SEGMENT;
DROP TABLE IF EXISTS MEAL;
DROP TABLE IF EXISTS DEPOSTI;

--FOREIGN KEY CREATION FOR BOOKINGS TABLE

ALTER TABLE BOOKINGS
	ADD CONSTRAINT fk_hotel
	FOREIGN KEY (hotel_id) 
	REFERENCES HOTEL(hotel_id)

ALTER TABLE BOOKINGS
	ADD CONSTRAINT fk_customer
    FOREIGN KEY (customer_id) 
	REFERENCES CUSTOMER(customer_id)

ALTER TABLE BOOKINGS
	ADD CONSTRAINT fk_room
    FOREIGN KEY (room_id) 
	REFERENCES ROOM(room_id)

ALTER TABLE BOOKINGS
	ADD CONSTRAINT fk_market
    FOREIGN KEY (market_id) 
	REFERENCES MARKET_SEGMENT(market_id)

ALTER TABLE BOOKINGS
	ADD CONSTRAINT fk_meal
    FOREIGN KEY (meal_id) 
	REFERENCES MEAL(meal_id)

ALTER TABLE BOOKINGS
	ADD CONSTRAINT fk_deposit
    FOREIGN KEY (deposit_id)
	REFERENCES DEPOSIT(deposit_id)

ALTER TABLE BOOKINGS 
	ADD CONSTRAINT fk_date
    FOREIGN KEY (date_id) 
	REFERENCES DATES(date_id)

--DATA CHECKING
SELECT * FROM BOOKINGS;
SELECT * FROM ROOM;
SELECT * FROM HOTEL;
SELECT * FROM MARKET_SEGMENT;
SELECT * FROM DEPOSIT;
SELECT * FROM MEAL;
SELECT * FROM CUSTOMER;
SELECT * FROM DATES;

